import { mockAssignments, mockClasses } from './mockData';

// Simulating API delay
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

// Mock fetch assignments
export const fetchAssignments = async () => {
  await delay(800);
  return [...mockAssignments];
};

// Mock fetch classes
export const fetchClasses = async () => {
  await delay(600);
  return [...mockClasses];
};

// Mock AI agent message
export const sendMessageToAgent = async (message, uploadedFiles) => {
  await delay(1200);
  
  // Simple response logic based on message content
  if (message.toLowerCase().includes('math')) {
    return {
      id: Date.now(),
      sender: 'agent',
      content: 'I can help you create a math assignment. Would you like to focus on algebra, geometry, or calculus?'
    };
  } 
  else if (message.toLowerCase().includes('science')) {
    return {
      id: Date.now(),
      sender: 'agent',
      content: 'Great! I can help with a science assignment. Let me know if you want to focus on biology, chemistry, or physics.'
    };
  }
  else if (message.toLowerCase().includes('generate') || message.toLowerCase().includes('create')) {
    return {
      id: Date.now(),
      sender: 'agent',
      content: 'I\'ve created a sample assignment based on your requirements. You can now edit it in the assignment editor below.',
      assignment: {
        title: 'Sample Assignment',
        content: `# Sample Assignment\n\n## Introduction\nThis is a sample assignment generated by the AI assistant. You can edit this content as needed.\n\n## Tasks\n1. First task description\n2. Second task description\n3. Third task description\n\n## Requirements\n- Requirement 1\n- Requirement 2\n- Requirement 3\n\n## Submission Guidelines\nSubmit your work by the due date in the specified format.`
      }
    };
  }
  else if (uploadedFiles && uploadedFiles.length > 0) {
    return {
      id: Date.now(),
      sender: 'agent',
      content: `I've analyzed the uploaded material${uploadedFiles.length > 1 ? 's' : ''}. What type of assignment would you like to create based on ${uploadedFiles.length > 1 ? 'these materials' : 'this material'}?`
    };
  }
  else {
    return {
      id: Date.now(),
      sender: 'agent',
      content: 'I\'m here to help you create assignments. Could you provide more details about what subject and topic you\'d like to focus on?'
    };
  }
};

// Mock save assignment
export const saveAssignmentToApi = async (assignment) => {
  await delay(1000);
  return {
    ...assignment,
    updatedAt: new Date().toISOString()
  };
};

// Mock post assignment
export const postAssignmentToApi = async (assignmentId) => {
  await delay(1200);
  return {
    success: true,
    postedAt: new Date().toISOString()
  };
};